import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
import Container from "components/ui/Container";
import Product from 'components/ui/Products/ProductBox';
import { useEffect } from 'react';
import { getProducts } from 'store/slices/cartSlice';
import { useDispatch, useSelector } from 'store/store';
import { IPost } from 'types';

let userStorageInfo:string|null;

export interface ProductType  {
    id: string;
    name: string;
    description: string;
    price: number;
    category: string;
    imgurl: string;
  };
  
// const [name, setName] = useState("")
// const [option, setOption] = useState("")



 

const Cart: NextPage = () => {
  // const notify = () => toast("Wow so easy!");
  
  
  const router = useRouter();
  const redirect = router.query.redirect as string;
  //const { state, dispatch } = useContext(StoreContext);
  //const { userInfo } = state;
 

  const dispatch = useDispatch();
//   const { name, email,  username } = useSelector(getUserState);
    
// const [productSet, setProductSet] = useState([]);
 
  const {  dataSet, isLoading, isError, isSuccess } = useSelector(
    (state) => state.cart
  )
  // console.log(dataSet);
  useEffect(() => {
    if (isError) {
      toast.error("There is error")
    }

   
    userStorageInfo =  localStorage.getItem("user");
   
    if (!userStorageInfo) {
      router.push(redirect || "/signup");       
    } 

     
    dispatch(
        getProducts()
        // setProductSet(dataSet)
      );


    // dispatch(reset())

    
  }, [isError,  dispatch])

 
  const addToCart = async (id: number) => {
    
    console.log(id)
     
  }
  return (
    <>
    <Container title="Dashboard">
        
      <Head>
        <title>Register Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" /> */}
      </Head>

      
      <h3  >
        Cart  
      </h3>
  
    
    {dataSet && dataSet.length > 0 ? (
      
          <div className='cartContainer'>
            {dataSet.map((data:IPost) => ( 
              <Product key={data.id} addToCart={addToCart}  item ={data}  />
            ))}
          </div>
        ) : (
          <h3>You have not set any goals</h3>
        )}

 
       
 
      </Container>
 
 </>
  )
}

export default Cart


 