import Container from "components/ui/Container";
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { toast, ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { getUserState } from '../store/slices/userSlice';
import { useDispatch, useSelector } from '../store/store';
import styles from '../styles/Home.module.css';

let userStorageInfo:string|null;


 
const Dashboard: NextPage = () => {
  // const notify = () => toast("Wow so easy!");
 
  
  const router = useRouter();
  const redirect = router.query.redirect as string;

  const dispatch = useDispatch();
  const { name, email,  username } = useSelector(getUserState);
  const {  userinfo, isLoading, isError, isSuccess } = useSelector(
    (state) => state.user
  )

  useEffect(() => {
    if (isError) {
      toast.error("There is error")
    }

    if (isSuccess) {
       router.push(redirect || "/dashboard");
    }
    
    userStorageInfo =  localStorage.getItem("user");

   
    if (userStorageInfo) {
      router.push(redirect || "/dashboard");       
    }else{
      router.push(redirect || "/login");
    }
    
  }, [dispatch])
    

  
 
  return (
    <Container title="Dashboard">
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
      
       
      <ToastContainer position="bottom-center" />
      
      <h3  >
        Sign Up Form  {name}
      </h3>

     
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>

    </Container>
  )
}

export default Dashboard


 